In [3]:
import numpy as np
from pyparsing import empty

In [18]:
-arr=np.array([1,2,3,4,5])
print(arr)

zeros=np.zeros((3,4))
print(zeros)

print(np.ones((3,4)))

print(np.empty((2,2)))

print(np.arange(10,20))

[1 2 3 4 5]
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]
[[0.00000000e+000 1.15849219e-311]
 [1.15849219e-311 1.15849219e-311]]
[10 11 12 13 14 15 16 17 18 19]


In [19]:
print(np.linspace(0,1,5))

[0.   0.25 0.5  0.75 1.  ]


In [20]:
arr=np.array([[1,2,3],[4,5,6]])
print(arr.reshape(3,2))



[[1 2]
 [3 4]
 [5 6]]


In [25]:
arr1=np.array([1,2,3])
arr2=np.array([4,5,6])
arr3=np.hstack((arr1,arr2))
print(arr3)
arr4=np.vstack((arr1,arr2))
print(arr4)

[1 2 3 4 5 6]
[[1 2 3]
 [4 5 6]]


In [26]:
s=np.random.normal(0,0.1,1000)
print(s)

[ 2.32551734e-02  1.17817471e-01 -1.42461871e-02  9.71719031e-02
 -1.66597905e-03 -2.15519193e-02 -4.03565406e-02  3.81503592e-02
 -6.07210782e-03  7.34632528e-02  4.21236039e-02  5.83433347e-02
 -2.27544015e-02  1.79672413e-01 -2.24963073e-02 -3.85742238e-02
  1.31609018e-01  1.59727512e-01 -6.87823242e-02  3.79889069e-02
 -1.00011985e-01  3.48552809e-02 -9.30712192e-02 -1.33304805e-01
 -1.10744619e-01 -5.80659886e-02 -4.07429568e-02  3.08396530e-02
  1.14683002e-01 -2.48785030e-01  8.56256065e-02 -1.21165845e-01
  7.95414906e-02 -1.11948726e-02  8.63558973e-02 -4.05284532e-02
 -4.97157107e-02 -9.50726197e-02 -7.79761065e-02 -1.25793908e-02
  7.26691625e-02  5.76160134e-02  1.45881866e-01 -1.22188245e-01
 -1.16620259e-02  8.22273455e-02  7.41715960e-02  1.60769724e-01
 -1.33263381e-01 -2.21087194e-02  2.11390370e-02 -4.95994274e-02
  3.66119276e-02 -5.47704618e-02 -1.10484195e-01 -1.64718606e-01
  1.68774135e-01 -2.26245726e-01  1.41475962e-01  1.21960533e-01
  1.09214897e-01 -1.00901

In [27]:
low, high, size = 1, 10, 5
random_integers = np.random.randint(low, high, size)
print(random_integers)

[1 5 6 7 1]


In [30]:
arr=np.array([1,2,3,4,5])
arr1=[1,2,3,4,5]
print(arr[arr>3])
print(list(filter(lambda x: x>3, arr1)))

[4 5]
[4, 5]


In [5]:
a=np.array([1,2,3])
b=np.array([4,5,6])
print(a+b)
print(a+1)


[5 7 9]
[2 3 4]
